import { Bell, Calendar, FileText, Folder, ListChecks, StickyNote } from "lucide-react";
import { USER_NAME } from "@/lib/app-constants";
import type { ArchiveCategoryInfo, ArchiveDateFilterOption, ArchiveItem, ArchiveStats } from "@/types/archive";

export const ARCHIVE_CATEGORIES: ArchiveCategoryInfo[] = [
  { key: "task", label: "Архив задач", icon: ListChecks },
  { key: "project", label: "Архив проектов", icon: Folder },
  { key: "note", label: "Архив заметок", icon: StickyNote },
  { key: "file", label: "Архив файлов", icon: FileText },
  { key: "event", label: "Архив событий", icon: Calendar },
  { key: "reminder", label: "Архив напоминаний", icon: Bell },
];

export const ARCHIVE_TYPE_LABELS: Record<ArchiveItem["type"], string> = {
  task: "Задача",
  project: "Проект",
  note: "Заметка",
  file: "Файл",
  event: "Событие",
  reminder: "Напоминание",
};

export const ARCHIVE_DATE_FILTERS: ArchiveDateFilterOption[] = [
  { key: "all", label: "Всё время" },
  { key: "7d", label: "За 7 дней" },
  { key: "30d", label: "За 30 дней" },
  { key: "90d", label: "За 3 месяца" },
  { key: "year", label: "За этот год" },
];

export const ARCHIVE_STATS: ArchiveStats = {
  lastCleanupLabel: "3 июня 2026",
  freeSpaceLabel: "7.2 ГБ свободно из 10 ГБ",
  freeSpaceUsedPercent: 28,
};

export function createMockArchiveItems(): ArchiveItem[] {
  return [
    {
      id: "a1",
      name: "Согласовать макет главной страницы",
      type: "task",
      project: "Редизайн Planly",
      tags: ["дизайн", "срочно"],
      createdAtLabel: "2 июня 2026",
      archivedAtLabel: "20 июля 2026",
      archivedAtKey: "2026-07-20",
      sizeKb: 12,
      author: USER_NAME,
    },
    {
      id: "a2",
      name: "Подготовить отчёт по спринту",
      type: "task",
      project: "Мобильное приложение",
      tags: ["отчёт"],
      createdAtLabel: "14 июня 2026",
      archivedAtLabel: "18 июля 2026",
      archivedAtKey: "2026-07-18",
      sizeKb: 8,
      author: USER_NAME,
    },
    {
      id: "a3",
      name: "Созвон с командой дизайна",
      type: "task",
      project: null,
      tags: [],
      createdAtLabel: "1 мая 2026",
      archivedAtLabel: "5 мая 2026",
      archivedAtKey: "2026-05-05",
      sizeKb: 4,
      author: USER_NAME,
    },
    {
      id: "a4",
      name: "Старый маркетинговый сайт",
      type: "project",
      project: null,
      tags: ["маркетинг", "2025"],
      createdAtLabel: "10 сентября 2025",
      archivedAtLabel: "12 января 2026",
      archivedAtKey: "2026-01-12",
      sizeKb: 4200,
      author: USER_NAME,
    },
    {
      id: "a5",
      name: "Исследование рынка Q1",
      type: "project",
      project: null,
      tags: ["исследование"],
      createdAtLabel: "3 января 2026",
      archivedAtLabel: "2 апреля 2026",
      archivedAtKey: "2026-04-02",
      sizeKb: 3100,
      author: USER_NAME,
    },
    {
      id: "a6",
      name: "Идеи для редизайна onboarding",
      type: "note",
      project: "Редизайн Planly",
      tags: ["идеи"],
      createdAtLabel: "22 мая 2026",
      archivedAtLabel: "19 июля 2026",
      archivedAtKey: "2026-07-19",
      sizeKb: 6,
      author: USER_NAME,
    },
    {
      id: "a7",
      name: "Черновик статьи для блога",
      type: "note",
      project: null,
      tags: ["контент", "черновик"],
      createdAtLabel: "8 марта 2026",
      archivedAtLabel: "15 марта 2026",
      archivedAtKey: "2026-03-15",
      sizeKb: 18,
      author: USER_NAME,
    },
    {
      id: "a8",
      name: "Заметки со встречи с инвесторами",
      type: "note",
      project: null,
      tags: [],
      createdAtLabel: "27 ноября 2025",
      archivedAtLabel: "1 декабря 2025",
      archivedAtKey: "2025-12-01",
      sizeKb: 9,
      author: USER_NAME,
    },
    {
      id: "a9",
      name: "brand-guidelines-v2.pdf",
      type: "file",
      project: "Редизайн Planly",
      tags: ["брендинг"],
      createdAtLabel: "30 апреля 2026",
      archivedAtLabel: "10 июля 2026",
      archivedAtKey: "2026-07-10",
      sizeKb: 5600,
      author: USER_NAME,
    },
    {
      id: "a10",
      name: "презентация-для-клиента.pptx",
      type: "file",
      project: "Маркетинговая кампания",
      tags: ["презентация"],
      createdAtLabel: "12 февраля 2026",
      archivedAtLabel: "20 февраля 2026",
      archivedAtKey: "2026-02-20",
      sizeKb: 8900,
      author: USER_NAME,
    },
    {
      id: "a11",
      name: "старый-логотип.png",
      type: "file",
      project: null,
      tags: ["архив"],
      createdAtLabel: "5 июня 2025",
      archivedAtLabel: "1 сентября 2025",
      archivedAtKey: "2025-09-01",
      sizeKb: 340,
      author: USER_NAME,
    },
    {
      id: "a12",
      name: "Питч-встреча с партнёрами",
      type: "event",
      project: null,
      tags: ["встреча"],
      createdAtLabel: "1 июня 2026",
      archivedAtLabel: "17 июля 2026",
      archivedAtKey: "2026-07-17",
      sizeKb: 3,
      author: USER_NAME,
    },
    {
      id: "a13",
      name: "Демо-день акселератора",
      type: "event",
      project: null,
      tags: [],
      createdAtLabel: "20 января 2026",
      archivedAtLabel: "28 января 2026",
      archivedAtKey: "2026-01-28",
      sizeKb: 3,
      author: USER_NAME,
    },
    {
      id: "a14",
      name: "Продлить подписку на хостинг",
      type: "reminder",
      project: null,
      tags: ["оплата"],
      createdAtLabel: "1 апреля 2026",
      archivedAtLabel: "5 апреля 2026",
      archivedAtKey: "2026-04-05",
      sizeKb: 2,
      author: USER_NAME,
    },
    {
      id: "a15",
      name: "Позвонить в поддержку хостинга",
      type: "reminder",
      project: null,
      tags: [],
      createdAtLabel: "10 июля 2026",
      archivedAtLabel: "12 июля 2026",
      archivedAtKey: "2026-07-12",
      sizeKb: 2,
      author: USER_NAME,
    },
    {
      id: "a16",
      name: "Тестовое покрытие модуля календаря",
      type: "task",
      project: "Мобильное приложение",
      tags: ["тесты", "срочно"],
      createdAtLabel: "5 июля 2026",
      archivedAtLabel: "21 июля 2026",
      archivedAtKey: "2026-07-21",
      sizeKb: 7,
      author: USER_NAME,
    },
  ];
}
