import {
  BarChart3,
  BookOpen,
  Globe,
  Megaphone,
  Palette,
  Rocket,
  Search,
  Smartphone,
  Users,
} from "lucide-react";
import type { Project } from "@/types/project";

// Static UI-only fixtures for the Projects page skeleton — no store, no
// persistence. Real project data/CRUD is a later task.
export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "Редизайн Planly",
    description: "Обновление интерфейса и системы компонентов приложения.",
    icon: Palette,
    color: "blue",
    status: "active",
    progress: 62,
    tasksDone: 8,
    tasksTotal: 13,
    deadlineLabel: "12 авг",
    starred: true,
  },
  {
    id: "p2",
    name: "Мобильное приложение",
    description: "Портирование основных сценариев планировщика на мобильные устройства.",
    icon: Smartphone,
    color: "purple",
    status: "active",
    progress: 34,
    tasksDone: 5,
    tasksTotal: 15,
    deadlineLabel: "20 сент",
    starred: false,
  },
  {
    id: "p3",
    name: "Маркетинговая кампания",
    description: "Запуск рекламной кампании к осеннему обновлению продукта.",
    icon: Megaphone,
    color: "orange",
    status: "active",
    progress: 78,
    tasksDone: 12,
    tasksTotal: 16,
    deadlineLabel: "1 авг",
    starred: false,
  },
  {
    id: "p4",
    name: "Исследование рынка",
    description: "Анализ конкурентов и опрос пользователей по ключевым сценариям.",
    icon: Search,
    color: "teal",
    status: "active",
    progress: 15,
    tasksDone: 2,
    tasksTotal: 12,
    deadlineLabel: "30 авг",
    starred: false,
  },
  {
    id: "p5",
    name: "Автоматизация отчётов",
    description: "Еженедельные отчёты по прогрессу собираются и рассылаются автоматически.",
    icon: BarChart3,
    color: "indigo",
    status: "active",
    progress: 45,
    tasksDone: 6,
    tasksTotal: 14,
    deadlineLabel: "10 сент",
    starred: false,
  },
  {
    id: "p6",
    name: "Сайт-визитка",
    description: "Лендинг с описанием продукта и формой обратной связи.",
    icon: Globe,
    color: "green",
    status: "completed",
    progress: 100,
    tasksDone: 10,
    tasksTotal: 10,
    deadlineLabel: "1 июля",
    starred: true,
  },
  {
    id: "p7",
    name: "Внутренняя база знаний",
    description: "Документация процессов и онбординг новых сотрудников.",
    icon: BookOpen,
    color: "pink",
    status: "completed",
    progress: 100,
    tasksDone: 7,
    tasksTotal: 7,
    deadlineLabel: "15 июня",
    starred: false,
  },
  {
    id: "p8",
    name: "Партнёрская программа",
    description: "Условия сотрудничества и первые переговоры с партнёрами.",
    icon: Users,
    color: "red",
    status: "onHold",
    progress: 20,
    tasksDone: 1,
    tasksTotal: 9,
    deadlineLabel: "—",
    starred: false,
  },
  {
    id: "p9",
    name: "Личный сайт",
    description: "Портфолио и блог — приостановлено до конца сезона.",
    icon: Rocket,
    color: "orange",
    status: "onHold",
    progress: 5,
    tasksDone: 1,
    tasksTotal: 8,
    deadlineLabel: "—",
    starred: false,
  },
];
